Console.Clear();
Console.WriteLine("Введите b1: ");
double b1 = double.Parse(Console.ReadLine()!);
Console.WriteLine("Введите k1: ");
double k1 = double.Parse(Console.ReadLine()!);
Console.WriteLine("Введите b2: ");
double b2 = double.Parse(Console.ReadLine()!);
Console.WriteLine("Введите k2: ");
double k2 = double.Parse(Console.ReadLine()!);
double x = (b2 - b1) / (k1 - k2);
double y = (x * k1) + b1;
Console.WriteLine($"Координаты точки пересечения заданных прямых: ({x}, {y})");